# themes from https://github.com/alacritty/alacritty-theme

general.import = ["~/.config/alacritty/themes/themes/slate.toml"]
general.live_config_reload = true

[font]
size = 20

[font.normal]
family = "0xProto Nerd Font"
style = "Regular"

[window]
decorations = "Buttonless"
startup_mode = "Maximized"
opacity = 0.75

[window.padding]
x = 3
y = 0

[cursor]
[cursor.style]
shape = "Underline"
blinking = "Always"

[mouse]
hide_when_typing = true

[terminal]
shell = "/bin/bash"
